# SPDX-FileCopyrightText: Â© 2024 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: BUSL-1.1

[project]
name = "ct_monitor"
version = "0.1.0"
dependencies = [
    "requests",
    "cryptography",
]

[project.scripts]
ct_monitor = "ct_monitor:main"
