version = 1
SPDX-PackageName = "dstack"
SPDX-PackageSupplier = "Phala Network <dstack@phala.network>"
SPDX-PackageDownloadLocation = "https://github.com/Dstack-TEE/dstack"

# Non source files

[[annotations]]
path = "**/*.md"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

[[annotations]]
path = "**/requirements.txt"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

[[annotations]]
path = [
    "**/package.json",
    "**/openapi.json",
    "**/tsconfig.json",
    "**/tsconfig.node.json",
    "**/tsconfig.browser.json",
    "kms/auth-eth-bun/.oxlintrc.json",
    "package-lock.json",
    "**/package-lock.json",
    "kms/auth-eth/.openzeppelin/unknown-2035.json",
    "kms/auth-mock/.oxlintrc.json",
    "kms/auth-simple/.oxlintrc.json",
    "kms/auth-simple/auth-config.example.json",
    "sdk/simulator/*.json",
    "sdk/go/go.sum",
    "kms/dstack-app/builder/shared/kms-pinned-packages.txt",
    "kms/dstack-app/builder/shared/qemu-pinned-packages.txt",
    "gateway/dstack-app/builder/shared/builder-pinned-packages.txt",
    "gateway/dstack-app/builder/shared/pinned-packages.txt",
]
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

[[annotations]]
path = [
    "gateway/templates/wg.conf",
    "guest-agent/templates/metrics.tpl",
    "key-provider-build/sgx_default_qcnl.conf",
]
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

[[annotations]]
path = [
    ".cursorrules",
    ".mailmap",
    "**/.gitignore",
    "**/.npmignore",
]
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

[[annotations]]
path = "basefiles/*"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

[[annotations]]
path = [
    "docs/security/dstack-audit.pdf",
    "dstack_Technical_Charter_Final_10-17-2025.pdf",
    "sdk/simulator/quote.hex",
    "sdk/simulator/attestation.bin",
    "ra-tls/assets/tdx_quote",
    "cc-eventlog/samples/ccel.bin",
    "cc-eventlog/samples/tpm_eventlog.bin",
    "tpm-attest/tests/tpm_quote_sample.bin",
    "tpm-qvl/certs/gcp-root-ca.pem",
    "dstack-attest/tests/nitro_attestation.bin",
    "dstack-attest/tests/nitro_attestation_dbg.bin",
    "nsm-attest/tests/nitro_attestation.bin",
    "nsm-qvl/tests/nitro_attestation.bin",
    "nsm-qvl/certs/AWS_NitroEnclaves_Root-G1.pem",
    "tpm-qvl/certs/AWS_NitroEnclaves_Root-G1.pem",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Artworks


[[annotations]]
path = [
    "docs/assets/**",
    "docs/security-guide/assets/**",
    "dstack-logo.svg",
]
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 The Project Contributors"
SPDX-License-Identifier = "BUSL-1.1"

# Scripts with SPDX-like content (false positive prevention)

[[annotations]]
path = "scripts/add-spdx-attribution.py"
SPDX-FileCopyrightText = "Â© 2025 Phala Network <dstack@phala.network>"
SPDX-License-Identifier = "BUSL-1.1"
precedence = "override"

# Vendor code

[[annotations]]
path = "kms/auth-eth/lib/openzeppelin-contracts-upgradeable/**"
SPDX-FileCopyrightText = "Copyright (c) 2016-2025 Zeppelin Group Ltd"
SPDX-License-Identifier = "BUSL-1.1"
precedence = "override"

[[annotations]]
path = "kms/auth-eth/lib/openzeppelin-foundry-upgrades/**"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "BUSL-1.1"
precedence = "override"

[[annotations]]
path = "kms/auth-eth/lib/forge-std/**"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "BUSL-1.1"
precedence = "override"

# Generated files

[[annotations]]
path = "kms/auth-eth/typechain-types/**"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.lockb"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.lockb"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.snap"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/src/generated.rs"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/src/generated/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "gateway/assets/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "guest-api/src/generated/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "dstack-util/tests/fixtures/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "verifier/fixtures/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "verifier/builder/shared/*.txt"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "guest-agent/fixtures/*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
